// Golden / parity test: proves the TypeScript sync port (lib/sync.ts) produces
// the SAME result as the Python reference (reference/sync_srt.py) on the real
// committed Tears-of-Steel fixture.
//
// It is fully decoupled from VAD and audio decoding: both sides consume the
// SAME pre-computed speech signal (test/fixtures/speech_signal.json), so this
// test spawns NO Python, NO ffmpeg, and loads NO WASM. It only reads committed
// JSON artifacts and runs pure TypeScript, so it passes anywhere `npm test` runs.
//
// The two committed artifacts are regenerated by:
//   node   test/oracle/gen_speech_signal.mjs   -> test/fixtures/speech_signal.json
//   python test/oracle/oracle.py               -> test/fixtures/expected.json
// See test/oracle/README.md.

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { parseSrt } from "../lib/srt";
import { analyze, bestOffsetForRatio, DEFAULT_RATIOS } from "../lib/sync";
import { SIGNAL_HZ } from "../lib/types";

const here = dirname(fileURLToPath(import.meta.url));
const fixtures = join(here, "fixtures");

// Must match test/oracle/oracle.py's MAX_OFFSET_S and analyze()'s default.
const MAX_OFFSET_S = 120;

interface RatioExpectation {
  label: string;
  ratio: number;
  offset: number;
  score: number;
}
interface Expected {
  meta: { signalHz: number; signalLength: number; maxOffsetS: number };
  best: RatioExpectation;
  all: RatioExpectation[];
}

function loadSpeechSignal(): Float32Array {
  const raw = JSON.parse(
    readFileSync(join(fixtures, "speech_signal.json"), "utf-8"),
  ) as { signalHz: number; length: number; signal: number[] };
  expect(raw.signalHz).toBe(SIGNAL_HZ);
  expect(raw.signal.length).toBe(raw.length);
  return Float32Array.from(raw.signal);
}

function loadExpected(): Expected {
  return JSON.parse(
    readFileSync(join(fixtures, "expected.json"), "utf-8"),
  ) as Expected;
}

// One SIGNAL_HZ step = 0.01s; offsets must agree to within one step.
const OFFSET_TOL_S = 1 / SIGNAL_HZ + 1e-9;
// Per-ratio score parity tolerance between scipy (Python) and fft.js (TS).
const SCORE_ABS_TOL = 1e-4;
const SCORE_REL_TOL = 1e-3;

describe("golden parity: lib/sync.ts vs reference/sync_srt.py", () => {
  const speech = loadSpeechSignal();
  const expected = loadExpected();
  const blocks = parseSrt(readFileSync(join(fixtures, "sample.srt"), "utf-8"));

  it("fixture metadata is consistent with the committed signal", () => {
    expect(speech.length).toBe(expected.meta.signalLength);
    expect(expected.meta.signalHz).toBe(SIGNAL_HZ);
    expect(expected.meta.maxOffsetS).toBe(MAX_OFFSET_S);
    // 10 SRT cues in the fixture.
    expect(blocks).toHaveLength(10);
  });

  it("per-ratio offset + score match the Python oracle for every ratio", () => {
    // Index the oracle's per-ratio table by label.
    const byLabel = new Map(expected.all.map((r) => [r.label, r]));
    // The TS DEFAULT_RATIOS must cover exactly the oracle's ratio set.
    expect(DEFAULT_RATIOS.map((r) => r.label).sort()).toEqual(
      expected.all.map((r) => r.label).sort(),
    );

    for (const { label, ratio } of DEFAULT_RATIOS) {
      const ref = byLabel.get(label)!;
      // ratio constants themselves must be identical.
      expect(ratio).toBeCloseTo(ref.ratio, 12);

      const { offset, score } = bestOffsetForRatio(
        speech,
        blocks,
        ratio,
        MAX_OFFSET_S,
      );

      // Offset: within one SIGNAL_HZ step.
      expect(Math.abs(offset - ref.offset)).toBeLessThanOrEqual(OFFSET_TOL_S);

      // Score: the key scipy-vs-fft.js numerical-parity check.
      const tol = SCORE_ABS_TOL + SCORE_REL_TOL * Math.abs(ref.score);
      expect(Math.abs(score - ref.score)).toBeLessThanOrEqual(tol);
    }
  });

  it("analyze() picks the same best ratio + offset as Python", () => {
    const result = analyze(speech, blocks, { maxOffset: MAX_OFFSET_S });

    // Best ratio label + value: exact match with the oracle.
    expect(result.best.label).toBe(expected.best.label);
    expect(result.best.ratio).toBeCloseTo(expected.best.ratio, 12);

    // Best offset: within one SIGNAL_HZ step.
    expect(Math.abs(result.best.offset - expected.best.offset)).toBeLessThanOrEqual(
      OFFSET_TOL_S,
    );

    // Best score: tight parity with scipy.
    const tol = SCORE_ABS_TOL + SCORE_REL_TOL * Math.abs(expected.best.score);
    expect(Math.abs(result.best.score - expected.best.score)).toBeLessThanOrEqual(
      tol,
    );

    // The full ranked table should agree label-for-label in order too.
    const rankedTs = result.all.map((r) => r.label);
    const rankedPy = [...expected.all]
      .sort((a, b) => b.score - a.score)
      .map((r) => r.label);
    expect(rankedTs).toEqual(rankedPy);
  });
});
